name: Build and Release React Native APK

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-apk:
    name: Build APK with EAS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Install Expo CLI
      run: npm install -g @expo/cli
      
    - name: Install EAS CLI
      run: npm install -g eas-cli
      
    - name: Create EAS build configuration
      run: |
        cat > eas.json << EOF
        {
          "cli": {
            "version": ">= 7.8.4"
          },
          "build": {
            "development": {
              "developmentClient": true,
              "distribution": "internal"
            },
            "preview": {
              "distribution": "internal",
              "android": {
                "buildType": "apk"
              }
            },
            "production": {
              "android": {
                "buildType": "apk"
              }
            }
          },
          "submit": {
            "production": {}
          }
        }
        EOF
        
    - name: Build APK locally with Expo
      run: |
        # Generate Android project
        npx expo prebuild --platform android --clear
        
        # Build APK using Gradle
        cd android
        ./gradlew assembleRelease
        
    - name: Find APK file
      id: find_apk
      run: |
        APK_PATH=$(find android/app/build/outputs/apk -name "*.apk" -type f | head -1)
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "Found APK at: $APK_PATH"
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: affirmation-app-apk
        path: ${{ steps.find_apk.outputs.apk_path }}
        retention-days: 30
        
    - name: Get APK info
      run: |
        APK_PATH="${{ steps.find_apk.outputs.apk_path }}"
        if [ -f "$APK_PATH" ]; then
          APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
          echo "APK Size: $APK_SIZE"
          echo "APK Location: $APK_PATH"
        else
          echo "APK file not found!"
          exit 1
        fi