name: Build and Release React Native APK

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-apk:
    name: Build React Native APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json
        
    - name: Install React Native dependencies
      working-directory: ./mobile
      run: npm ci
      
    - name: Cache Gradle Wrapper
      uses: actions/cache@v4
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('mobile/android/gradle/wrapper/gradle-wrapper.properties') }}
        
    - name: Cache Gradle Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('mobile/android/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
          
    - name: Make Gradlew Executable
      working-directory: ./mobile/android
      run: chmod +x ./gradlew
      
    - name: Build Android APK
      working-directory: ./mobile
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: affirmation-react-native-apk
        path: mobile/android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Get APK info
      run: |
        APK_SIZE=$(du -h mobile/android/app/build/outputs/apk/release/app-release.apk | cut -f1)
        echo "APK Size: $APK_SIZE"
        echo "APK Location: mobile/android/app/build/outputs/apk/release/app-release.apk"