name: Build APK

on:
  push:
    branches:
      - main
      - copilot/**
  workflow_dispatch:

jobs:
  build:
    name: Build release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter/apk/release/app-release.apk
